# install with conda env create -f environment.yml 
name: '575-project-query'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - ipykernel
  - pandas
  - requests
  - faiss-cpu
  - rank-bm25
  - pyarrow
  - nltk
  - spacy
  - joblib
  - pip:
    - python-dotenv
    - langchain-core
    - langchain-community
    - langchain-huggingface
    - streamlit