# install with conda env create -f 575-project-query.yml 
name: '575-project-query'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - ipykernel
  - pandas
  - requests
  - faiss-cpu
  - pip:
    - python-dotenv
    - langchain-community
    - langchain-huggingface